const posts = [
    {
      name: "Post Title 1",
      postedBy: "User1",
      images: ["image1.jpg", "image2.jpg"],
      date: "2025-01-24",
      content: "This is the content for post 1. It provides detailed information about the topic discussed in this post. The purpose is to engage the audience and encourage them to share their thoughts. Content like this helps spark conversations and build connections within the community. We aim to provide value with each post, ensuring readers take something meaningful away. Whether it’s tips, advice, or stories, there’s always something to learn. Posts with thoughtful content inspire readers to interact more, contributing to a thriving online environment.",
      likes: 120,
      replies: 45,
      shared: 30,
    },
    {
      name: "Post Title 2",
      postedBy: "User2",
      images: ["image3.jpg"],
      date: "2025-01-23",
      content: "This is the content for post 2. It discusses an intriguing topic relevant to the audience. The goal is to provide insights, share experiences, or deliver educational material in a concise yet comprehensive manner. Engaging content encourages readers to interact, reply, and share. This post is structured to catch attention and offer value. Whether you’re seeking entertainment or knowledge, this post has you covered. Posts like this foster meaningful interactions, creating a space for sharing ideas and building strong connections online.",
      likes: 85,
      replies: 20,
      shared: 15,
    },
    {
      name: "Post Title 3",
      postedBy: "User3",
      images: ["image4.jpg", "image5.jpg", "image6.jpg"],
      date: "2025-01-22",
      content: "This is the content for post 3. It dives into a thought-provoking discussion about a trending subject. The post aims to educate and inspire readers, offering new perspectives or actionable tips. Writing with depth and clarity ensures readers stay engaged. Content creation like this involves research and passion to deliver valuable insights. Each post is crafted to make an impact, whether it’s entertaining, informing, or sparking debates. By sharing real stories or ideas, we encourage the audience to think critically and contribute meaningfully.",
      likes: 150,
      replies: 60,
      shared: 40,
    },
    {
      name: "Post Title 4",
      postedBy: "User4",
      images: [],
      date: "2025-01-21",
      content: "This is the content for post 4. It brings attention to a lesser-known but important topic. The post serves as a platform for raising awareness and sharing ideas. Engaging content starts with understanding the audience’s needs and interests, and this post delivers on that promise. With a mix of factual information and personal insight, the goal is to spark curiosity and prompt further exploration. Posts like this create opportunities for learning and open discussions. By focusing on relatable themes, we make connections that matter.",
      likes: 30,
      replies: 10,
      shared: 5,
    },
    {
      name: "Post Title 5",
      postedBy: "User5",
      images: ["image7.jpg"],
      date: "2025-01-20",
      content: "This is the content for post 5. It tells a story that resonates with the audience, drawing them into the narrative. The focus is on crafting a relatable and engaging piece that captures attention from start to finish. Effective storytelling involves vivid descriptions, emotional connections, and a clear message. Posts like this inspire readers to reflect, comment, and share. By weaving together facts and creativity, we ensure the content is both informative and entertaining. Every post is an opportunity to connect with readers on a deeper level.",
      likes: 70,
      replies: 25,
      shared: 20,
    },
    {
      name: "Post Title 6",
      postedBy: "User6",
      images: ["image8.jpg", "image9.jpg"],
      date: "2025-01-19",
      content: "This is the content for post 6. It highlights a fascinating subject, presenting ideas in an engaging and easy-to-read format. Posts like this aim to create a balance between education and entertainment, offering readers something of value. Crafting meaningful content takes effort, from selecting topics to writing and editing. Every detail matters when it comes to making an impact. This post encourages the audience to participate, fostering a sense of community. By focusing on quality and relevance, we ensure that the content resonates with readers.",
      likes: 200,
      replies: 80,
      shared: 50,
    },
    {
      name: "Post Title 7",
      postedBy: "User7",
      images: [],
      date: "2025-01-18",
      content: "This is the content for post 7. It explores an important theme, offering fresh insights and perspectives. Posts like this aim to educate, inform, or entertain, depending on the audience's preferences. Each piece is written with care to engage readers and prompt interaction. Quality content helps build trust and credibility, encouraging readers to come back for more. This post is designed to spark curiosity and foster meaningful discussions, inviting everyone to share their thoughts and experiences. Together, we create a vibrant and interactive online space.",
      likes: 40,
      replies: 15,
      shared: 10,
    },
    {
      name: "Post Title 8",
      postedBy: "User8",
      images: ["image10.jpg", "image11.jpg", "image12.jpg"],
      date: "2025-01-17",
      content: "This is the content for post 8. It provides a deep dive into a subject that’s both timely and relevant. Posts like this are designed to captivate the audience, offering a mix of interesting facts, personal experiences, and actionable advice. Writing with clarity and enthusiasm ensures readers stay engaged from start to finish. The content is structured to inform and inspire, leaving readers with something valuable to take away. By creating thoughtful posts, we foster a sense of community and encourage meaningful interactions.",
      likes: 180,
      replies: 70,
      shared: 60,
    },
    {
      name: "Post Title 9",
      postedBy: "User9",
      images: ["image13.jpg"],
      date: "2025-01-16",
      content: "This is the content for post 9. It shares insights on a topic that’s sure to spark interest and engagement. By combining storytelling with factual information, this post delivers value to its readers. Thoughtful content creation involves understanding the audience and presenting ideas in an engaging way. Each post is an opportunity to connect with readers, encouraging them to reflect, respond, and share. Posts like this play a crucial role in fostering online conversations and building a strong sense of community.",
      likes: 90,
      replies: 35,
      shared: 25,
    },
    {
      name: "Post Title 10",
      postedBy: "User10",
      images: [],
      date: "2025-01-15",
      content: "This is the content for post 10. It’s a compelling piece that blends information and entertainment to create an engaging read. The goal is to leave readers with something memorable, whether it’s a new idea, a fresh perspective, or simply a moment of enjoyment. Posts like this are crafted to stand out, with attention to detail in both writing and presentation. By focusing on the audience's needs, we create content that resonates and inspires action. Every post is an opportunity to connect and engage.",
      likes: 55,
      replies: 18,
      shared: 12,
    },
  ];
  
  
module.exports=posts;  